import streamlit as st

# حماية الصفحة
if "logged_in" not in st.session_state or not st.session_state.logged_in:
    st.error("يجب تسجيل الدخول للوصول إلى هذه الصفحة.")
    st.stop()

from supabase import create_client
from datetime import date

# ============================
# 🔗 الاتصال بـ Supabase
# ============================
url = st.secrets["SUPABASE_URL"]
key = st.secrets["SUPABASE_KEY"]
supabase = create_client(url, key)

st.set_page_config(page_title="إدارة المصاريف", page_icon="💸", layout="wide")
st.markdown("<h2 style='text-align:right;'>💸 إدارة المصاريف</h2>", unsafe_allow_html=True)

# ============================
# 🛠 التأكد من وجود جدول المصاريف
# ============================
def ensure_expenses_table():
    query = """
    CREATE TABLE IF NOT EXISTS expenses (
        id integer generated by default as identity primary key,
        expense_type text not null,
        amount numeric not null,
        notes text,
        date_added date default now(),
        added_by text,
        unit_no text,
        booking_id integer
    );
    """
    try:
        supabase.rpc("execute_sql", {"sql": query}).execute()
    except:
        pass

ensure_expenses_table()

# تحميل الوحدات
units = supabase.table("units_names").select("*").execute().data
unit_list = [u["unit_no"] for u in units]

# تحميل الحجوزات
bookings = supabase.table("bookings").select("*").order("id", desc=True).execute().data
booking_list = {f"{b['id']} - {b['client_name']}": b["id"] for b in bookings}

# ============================
# 📌 إضافة مصروف جديد
# ============================
st.subheader("➕ إضافة مصروف جديد")

col1, col2 = st.columns(2)

with col1:
    expense_type = st.text_input("نوع المصروف")
    amount = st.number_input("المبلغ", min_value=0.0, value=0.0)

with col2:
    date_added = st.date_input("تاريخ الإضافة", date.today())
    notes = st.text_area("ملاحظات")

# اختيار نوع الربط
st.write("### 🔗 ربط المصروف")
link_type = st.radio("اختر نوع الربط", ["مصروف على الحجز", "مصروف على الوحدة"])

selected_unit = None
selected_booking = None

if link_type == "مصروف على الوحدة":
    selected_unit = st.selectbox("اختر الوحدة", unit_list)

elif link_type == "مصروف على الحجز":
    selected_booking = st.selectbox("اختر الحجز", list(booking_list.keys()))

if st.button("💾 حفظ المصروف"):
    data = {
        "expense_type": expense_type,
        "amount": amount,
        "notes": notes,
        "date_added": str(date_added),
        "added_by": st.session_state.get("username", "admin"),
        "unit_no": selected_unit,
        "booking_id": booking_list.get(selected_booking) if selected_booking else None
    }

    supabase.table("expenses").insert(data).execute()
    st.success("تم حفظ المصروف بنجاح.")
    st.experimental_rerun()

# ============================
# 📋 عرض المصاريف
# ============================
st.write("---")
st.subheader("📋 قائمة المصاريف")

expenses = supabase.table("expenses").select("*").order("id", desc=True).execute().data

if not expenses:
    st.info("لا توجد مصاريف مسجلة.")
    st.stop()

for exp in expenses:
    title = f"💸 مصروف رقم {exp['id']} — {exp['expense_type']} — {exp['amount']} ريال"

    if exp.get("unit_no"):
        title += f" — وحدة {exp['unit_no']}"

    if exp.get("booking_id"):
        title += f" — حجز {exp['booking_id']}"

    with st.expander(title):

        colA, colB = st.columns(2)

        with colA:
            new_type = st.text_input("نوع المصروف", exp["expense_type"], key=f"type_{exp['id']}")
            new_amount = st.number_input("المبلغ", min_value=0.0, value=float(exp["amount"]), key=f"amount_{exp['id']}")

        with colB:
            new_date = st.date_input("التاريخ", date.fromisoformat(exp["date_added"]), key=f"date_{exp['id']}")
            new_notes = st.text_area("ملاحظات", exp.get("notes", ""), key=f"notes_{exp['id']}")

        # تعديل الربط
        st.write("### 🔗 تعديل الربط")

        new_link_type = st.radio(
            "نوع الربط",
            ["مصروف على الحجز", "مصروف على الوحدة"],
            key=f"link_{exp['id']}",
            index=0 if exp.get("booking_id") else 1
        )

        new_unit = None
        new_booking = None

        if new_link_type == "مصروف على الوحدة":
            new_unit = st.selectbox("اختر الوحدة", unit_list, key=f"unit_{exp['id']}")
        else:
            new_booking = st.selectbox("اختر الحجز", list(booking_list.keys()), key=f"booking_{exp['id']}")

        # ============================
        # ✏️ تعديل المصروف
        # ============================
        if st.button("💾 حفظ التعديلات", key=f"save_{exp['id']}"):
            supabase.table("expenses").update({
                "expense_type": new_type,
                "amount": new_amount,
                "date_added": str(new_date),
                "notes": new_notes,
                "unit_no": new_unit,
                "booking_id": booking_list.get(new_booking) if new_booking else None
            }).eq("id", exp["id"]).execute()

            st.success("تم تحديث المصروف بنجاح.")
            st.experimental_rerun()

        # ============================
        # 🗑️ حذف المصروف
        # ============================
        if st.button("🗑️ حذف المصروف", key=f"delete_{exp['id']}"):
            supabase.table("expenses").delete().eq("id", exp["id"]).execute()
            st.error("تم حذف المصروف.")
            st.experimental_rerun()
